package com.example.myapp2;

public class ListaAnime {
    public static String[][] getNombre(){
        return new String[][] {
                {"Angel Beats!","Drama, Escolar","13 capítulos","4.7","Cuando Otonashi despierta en una escuela desconocida y sin recuerdos, la situación que tiene frente a él es completamente caótica: un grupo de estudiantes le dice que está muerto, que está en el más allá y que debe pelear si no quiere ser aniquilado. ¿El enemigo? Ángel, enviada de Dios y cuya misión es que estos jóvenes acepten sus injustas muertes. Pero en el más allá también se puede hacer vida escolar corriente... o al menos dentro de unos márgenes aceptables para alguien supuestamente muerto que quiere enfrentarse a Dios. ¡Bienvenido al Frente de los No Muertos!"},
                {"Another","Gore, Terror","12 capítulos","4.6","La historia se centra en una clase maldita y en los hilos del destino que llevan hasta a la muerte a todos los alumnos de la misma. Hace 26 años iba a esa clase una chica llamada Misaki. Buena deportista, popular, le caía bien a todo el mundo, sacaba las mejores notas... Pero un día murió dejando un vacío enorme en sus compañeros de clases. Estos, decididos a no olvidarla, siguieron actuando como si Misaki siguiera viva hasta la graduación."},
                {"Clannad","Drama, Escolar","23 capítulos","4.1","Tomoya Okazaki es un joven de tercer año de instituto que parece importarle poco su desempeño escolar, y sumada a su actitud conflictiva originada por problemas familiares, es marcado como “delincuente” en su escuela por la gran mayoría de sus compañeros que están más ocupados pensando en lo que harán una vez acaben la escuela. Tomoya, sin amigos, oficio ni beneficio; conoce providencialmente a Nagisa Furukawa, una chica enfermiza algo lenta en los estudios que se quedó sin amigos puesto que todos ellos ya se habían graduado. Poco a poco ambos entablan amistad y mientras el joven empieza a descubrir que su escuela no era tan mal como aparentaba, empieza a conocer a mas chicas. Sin embargo, a pesar de todo, el muchacho y sus amigas guardan secretos, sueños y deseos que iran entrecruzandose."},
                {"Dragon Ball Z","Shonen, Acción","13 capítulos","4.7","Cuando Otonashi despierta en una escuela desconocida y sin recuerdos, la situación que tiene frente a él es completamente caótica: un grupo de estudiantes le dice que está muerto, que está en el más allá y que debe pelear si no quiere ser aniquilado. ¿El enemigo? Ángel, enviada de Dios y cuya misión es que estos jóvenes acepten sus injustas muertes. Pero en el más allá también se puede hacer vida escolar corriente... o al menos dentro de unos márgenes aceptables para alguien supuestamente muerto que quiere enfrentarse a Dios. ¡Bienvenido al Frente de los No Muertos!"},
                {"Elfen Lied","Gore, Drama","13 capítulos","4.7","Cuando Otonashi despierta en una escuela desconocida y sin recuerdos, la situación que tiene frente a él es completamente caótica: un grupo de estudiantes le dice que está muerto, que está en el más allá y que debe pelear si no quiere ser aniquilado. ¿El enemigo? Ángel, enviada de Dios y cuya misión es que estos jóvenes acepten sus injustas muertes. Pero en el más allá también se puede hacer vida escolar corriente... o al menos dentro de unos márgenes aceptables para alguien supuestamente muerto que quiere enfrentarse a Dios. ¡Bienvenido al Frente de los No Muertos!"},
                {"Fairy Tail","Shonen, Comedia","13 capítulos","4.7","Cuando Otonashi despierta en una escuela desconocida y sin recuerdos, la situación que tiene frente a él es completamente caótica: un grupo de estudiantes le dice que está muerto, que está en el más allá y que debe pelear si no quiere ser aniquilado. ¿El enemigo? Ángel, enviada de Dios y cuya misión es que estos jóvenes acepten sus injustas muertes. Pero en el más allá también se puede hacer vida escolar corriente... o al menos dentro de unos márgenes aceptables para alguien supuestamente muerto que quiere enfrentarse a Dios. ¡Bienvenido al Frente de los No Muertos!"},
                {"Full Metal Alchemist","Drama, Fantasía","13 capítulos","4.7","Cuando Otonashi despierta en una escuela desconocida y sin recuerdos, la situación que tiene frente a él es completamente caótica: un grupo de estudiantes le dice que está muerto, que está en el más allá y que debe pelear si no quiere ser aniquilado. ¿El enemigo? Ángel, enviada de Dios y cuya misión es que estos jóvenes acepten sus injustas muertes. Pero en el más allá también se puede hacer vida escolar corriente... o al menos dentro de unos márgenes aceptables para alguien supuestamente muerto que quiere enfrentarse a Dios. ¡Bienvenido al Frente de los No Muertos!"},
                {"Inuyasha","Drama, Fantasía","13 capítulos","4.7","Cuando Otonashi despierta en una escuela desconocida y sin recuerdos, la situación que tiene frente a él es completamente caótica: un grupo de estudiantes le dice que está muerto, que está en el más allá y que debe pelear si no quiere ser aniquilado. ¿El enemigo? Ángel, enviada de Dios y cuya misión es que estos jóvenes acepten sus injustas muertes. Pero en el más allá también se puede hacer vida escolar corriente... o al menos dentro de unos márgenes aceptables para alguien supuestamente muerto que quiere enfrentarse a Dios. ¡Bienvenido al Frente de los No Muertos!"},
                {"Kaichou wa Maid-Sama","Comedia, Romance","13 capítulos","4.7","Cuando Otonashi despierta en una escuela desconocida y sin recuerdos, la situación que tiene frente a él es completamente caótica: un grupo de estudiantes le dice que está muerto, que está en el más allá y que debe pelear si no quiere ser aniquilado. ¿El enemigo? Ángel, enviada de Dios y cuya misión es que estos jóvenes acepten sus injustas muertes. Pero en el más allá también se puede hacer vida escolar corriente... o al menos dentro de unos márgenes aceptables para alguien supuestamente muerto que quiere enfrentarse a Dios. ¡Bienvenido al Frente de los No Muertos!"},
                {"Nanatsu no Taizai","Shonen","13 capítulos","4.7","Cuando Otonashi despierta en una escuela desconocida y sin recuerdos, la situación que tiene frente a él es completamente caótica: un grupo de estudiantes le dice que está muerto, que está en el más allá y que debe pelear si no quiere ser aniquilado. ¿El enemigo? Ángel, enviada de Dios y cuya misión es que estos jóvenes acepten sus injustas muertes. Pero en el más allá también se puede hacer vida escolar corriente... o al menos dentro de unos márgenes aceptables para alguien supuestamente muerto que quiere enfrentarse a Dios. ¡Bienvenido al Frente de los No Muertos!"},
                {"Nisekoi","Comedia, Romance","13 capítulos","4.7","Cuando Otonashi despierta en una escuela desconocida y sin recuerdos, la situación que tiene frente a él es completamente caótica: un grupo de estudiantes le dice que está muerto, que está en el más allá y que debe pelear si no quiere ser aniquilado. ¿El enemigo? Ángel, enviada de Dios y cuya misión es que estos jóvenes acepten sus injustas muertes. Pero en el más allá también se puede hacer vida escolar corriente... o al menos dentro de unos márgenes aceptables para alguien supuestamente muerto que quiere enfrentarse a Dios. ¡Bienvenido al Frente de los No Muertos!"},
                {"No Game No Life","Videojuegos, Comedia","13 capítulos","4.7","Cuando Otonashi despierta en una escuela desconocida y sin recuerdos, la situación que tiene frente a él es completamente caótica: un grupo de estudiantes le dice que está muerto, que está en el más allá y que debe pelear si no quiere ser aniquilado. ¿El enemigo? Ángel, enviada de Dios y cuya misión es que estos jóvenes acepten sus injustas muertes. Pero en el más allá también se puede hacer vida escolar corriente... o al menos dentro de unos márgenes aceptables para alguien supuestamente muerto que quiere enfrentarse a Dios. ¡Bienvenido al Frente de los No Muertos!"},
                {"One Piece","Shonen, Aventura","13 capítulos","4.7","Cuando Otonashi despierta en una escuela desconocida y sin recuerdos, la situación que tiene frente a él es completamente caótica: un grupo de estudiantes le dice que está muerto, que está en el más allá y que debe pelear si no quiere ser aniquilado. ¿El enemigo? Ángel, enviada de Dios y cuya misión es que estos jóvenes acepten sus injustas muertes. Pero en el más allá también se puede hacer vida escolar corriente... o al menos dentro de unos márgenes aceptables para alguien supuestamente muerto que quiere enfrentarse a Dios. ¡Bienvenido al Frente de los No Muertos!"},
                {"Ouran High School Host Club","Comedia, Romance","13 capítulos","4.7","Cuando Otonashi despierta en una escuela desconocida y sin recuerdos, la situación que tiene frente a él es completamente caótica: un grupo de estudiantes le dice que está muerto, que está en el más allá y que debe pelear si no quiere ser aniquilado. ¿El enemigo? Ángel, enviada de Dios y cuya misión es que estos jóvenes acepten sus injustas muertes. Pero en el más allá también se puede hacer vida escolar corriente... o al menos dentro de unos márgenes aceptables para alguien supuestamente muerto que quiere enfrentarse a Dios. ¡Bienvenido al Frente de los No Muertos!"},
                {"Overlord","Comedia, Ecchi","13 capítulos","4.7","Cuando Otonashi despierta en una escuela desconocida y sin recuerdos, la situación que tiene frente a él es completamente caótica: un grupo de estudiantes le dice que está muerto, que está en el más allá y que debe pelear si no quiere ser aniquilado. ¿El enemigo? Ángel, enviada de Dios y cuya misión es que estos jóvenes acepten sus injustas muertes. Pero en el más allá también se puede hacer vida escolar corriente... o al menos dentro de unos márgenes aceptables para alguien supuestamente muerto que quiere enfrentarse a Dios. ¡Bienvenido al Frente de los No Muertos!"},
                {"Sword Art Online","Videojuegos, Drama","13 capítulos","4.7","Cuando Otonashi despierta en una escuela desconocida y sin recuerdos, la situación que tiene frente a él es completamente caótica: un grupo de estudiantes le dice que está muerto, que está en el más allá y que debe pelear si no quiere ser aniquilado. ¿El enemigo? Ángel, enviada de Dios y cuya misión es que estos jóvenes acepten sus injustas muertes. Pero en el más allá también se puede hacer vida escolar corriente... o al menos dentro de unos márgenes aceptables para alguien supuestamente muerto que quiere enfrentarse a Dios. ¡Bienvenido al Frente de los No Muertos!"},
                {"Shingeki no Kyojin","Acción","13 capítulos","4.7","Cuando Otonashi despierta en una escuela desconocida y sin recuerdos, la situación que tiene frente a él es completamente caótica: un grupo de estudiantes le dice que está muerto, que está en el más allá y que debe pelear si no quiere ser aniquilado. ¿El enemigo? Ángel, enviada de Dios y cuya misión es que estos jóvenes acepten sus injustas muertes. Pero en el más allá también se puede hacer vida escolar corriente... o al menos dentro de unos márgenes aceptables para alguien supuestamente muerto que quiere enfrentarse a Dios. ¡Bienvenido al Frente de los No Muertos!"},
                {"Soul Eater","Comedia, Acción","13 capítulos","4.7","Cuando Otonashi despierta en una escuela desconocida y sin recuerdos, la situación que tiene frente a él es completamente caótica: un grupo de estudiantes le dice que está muerto, que está en el más allá y que debe pelear si no quiere ser aniquilado. ¿El enemigo? Ángel, enviada de Dios y cuya misión es que estos jóvenes acepten sus injustas muertes. Pero en el más allá también se puede hacer vida escolar corriente... o al menos dentro de unos márgenes aceptables para alguien supuestamente muerto que quiere enfrentarse a Dios. ¡Bienvenido al Frente de los No Muertos!"},
                {"Toradora","Comedia, Romance","13 capítulos","4.7","Cuando Otonashi despierta en una escuela desconocida y sin recuerdos, la situación que tiene frente a él es completamente caótica: un grupo de estudiantes le dice que está muerto, que está en el más allá y que debe pelear si no quiere ser aniquilado. ¿El enemigo? Ángel, enviada de Dios y cuya misión es que estos jóvenes acepten sus injustas muertes. Pero en el más allá también se puede hacer vida escolar corriente... o al menos dentro de unos márgenes aceptables para alguien supuestamente muerto que quiere enfrentarse a Dios. ¡Bienvenido al Frente de los No Muertos!"},
        };
    }
}
